# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local connections
local   all             all                                     trust
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5

# App connections from Docker network
host    all             all             0.0.0.0/0               md5

# Replication — allow replica from anywhere in the Docker network
host    replication     replicator      0.0.0.0/0               md5
